### ISSUE TITLE
"object rest/spread properties" is not supported by default in Node.js v8.2.1

### ISSUE THREAD

**Issue by shsfre09** [storybooks/generate-page-webpack-plugin#2]
### Summary
In Node.js v8.2.1, "object rest/spread properties" is not supported by default, `--harmony` option is needed.
https://node.green/#ES2018-features-object-rest-spread-properties

So `@storybook/vue` fails to run the following:
```
>npm run storybook

some-project\node_modules\generate-page-webpack-plugin\index.js:37
              ...acc,
              ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> 
```

### Workaround
Currently, I call the command of `start-storybook` and `build-storybook` directly with `--harmony` option.
But if possible, I want you to support officially.
```
{
  "scripts": {
    "storybook": "node --harmony ./node_modules/@storybook/vue/bin/index.js -p 9001 -c .storybook",
    "build-storybook": "node --harmony ./node_modules/@storybook/vue/bin/build.js -c .storybook -o .out"
  }
}
```

**Comment by gihbatalha** [comment]
Hi @ndelangen. I installed version 1.1.0 and @storybook/vue fails to run.
Seems that Object.assign is missing in another part.

`
> npm run storybook
/project/node_modules/generate-page-webpack-plugin/index.js:48
            options: { ...options, ...value.options },
                       ^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous>
`

**Comment by OllieJennings** [comment]
This is still an issue, can we get all Object spreads removed?
